### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by dmstoykov** [codemerx/CodemerxDecompile#53]
- [x] - reword enospc instructions file
- [x] - strong name signing should be done with private key, not with public one
- [x] - kill server gracefully when app is killed with Cmd/Ctrl + C/Q
- [x] - Replace default electron app icon on windows with codemerx icon

**Comment by atdimitrov** [comment]
Done
